tau: 3					# tau
addrBits: 12			# bit length of record address
w: 4					# number of tuples in each bucket
dBytes: 4 				# record D bytes in the last tree

insert: 1000			# number of records to be initially inserted (-1 means insert max number)
stash: 16				# stash size